# Generated by Django 5.1 on 2024-09-13 15:06

import django.db.models.deletion
import marlin_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marlin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.ForeignKey(default=marlin_app.models.UserProfile.get_default_user_type, on_delete=django.db.models.deletion.CASCADE, to='marlin_app.usertype'),
        ),
    ]
