# Generated by Django 5.1 on 2024-10-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marlin_app', '0002_alter_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='status',
            field=models.CharField(choices=[('Aceptado', 'Aceptado'), ('Rechazado', 'Rechazado'), ('Pendiente', 'Pendiente'), ('Inactivo', 'Inactivo')], default='Pendiente', max_length=100),
        ),
    ]
