# Generated by Django 5.1 on 2024-11-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marlin_app', '0004_alter_storeitem_store_id_deliveryprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryprofile',
            name='brand',
            field=models.CharField(default='hola', max_length=100),
            preserve_default=False,
        ),
    ]
