# Generated by Django 5.1 on 2024-11-02 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marlin_app', '0005_deliveryprofile_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_num',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='store_id',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='marlin_app.store'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_variation_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marlin_app.itemvariation'),
        ),
    ]
