# Generated by Django 5.1 on 2024-11-02 00:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marlin_app', '0006_order_order_num_order_store_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='voucher',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
