# Generated by Django 5.1 on 2024-11-11 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marlin_app', '0007_order_voucher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_distance',
            field=models.CharField(default=1000, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='user_coordinates',
            field=models.CharField(default=(9.9803832, -84.768784), max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Buscando repartidor', 'Buscando repartidor'), ('En camino', 'En camino'), ('Entregado', 'Entregado'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=100),
        ),
    ]
