# Generated by Django 5.1 on 2024-11-12 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marlin_app', '0008_order_delivery_distance_order_delivery_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryprofile',
            name='coordinates',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliveryprofile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
