# Generated by Django 5.1 on 2024-11-13 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marlin_app', '0009_deliveryprofile_coordinates_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pendiente', max_length=20)),
                ('delivery_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marlin_app.deliveryprofile')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marlin_app.order')),
            ],
        ),
    ]
